<a href="https://colab.research.google.com/github/desaraju02/nlp/blob/main/Kindle_Reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

# Strategy
 - Preprocessing
 - Train test split
 - BOW, TF-IDF, Word2Vec
 - Train ML Algo

In [4]:
data = pd.read_csv('all_kindle_review.csv')

In [5]:
data

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [23]:
df = data[['reviewText','rating']]

In [24]:
df

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [25]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [26]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [27]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

# Preprocessing and Cleaning


# Positive review is 1 and negative is 0

In [28]:
df['rating'] = df['rating'].apply(lambda x: 1 if x>3 else 0)

/tmp/ipython-input-28-1672273239.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x: 1 if x>3 else 0)


In [29]:
df

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       0
1      Great short read.  I didn't want to put it dow...       1
2      I'll start by saying this is the first of four...       0
3      Aggie is Angela Lansbury who carries pocketboo...       0
4      I did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       1
11996  I have read all seven books in this series. Ap...       1
11997  This book really just wasn't my cuppa.  The si...       0
11998  tried to use it to charge my kindle, it didn't...       0
11999  Taking Instruction is a look into the often hi...       0

[12000 rows x 2 columns]

In [30]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [31]:
df['reviewText']= df['reviewText'].str.lower()

/tmp/ipython-input-31-2403061003.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']= df['reviewText'].str.lower()


In [35]:
import re
from bs4 import BeautifulSoup
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [36]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

/tmp/ipython-input-36-3736800740.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
/tmp/ipython-input-36-3736800740.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
/tmp/ipython-input-36-3736800740.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try us

In [37]:
df

reviewText  rating
0      jace rankin may short hes nothing mess man hau...       0
1      great short read didnt want put read one sitti...       1
2      ill start saying first four books wasnt expect...       0
3      aggie angela lansbury carries pocketbooks inst...       0
4      expect type book library pleased find price right       1
...                                                  ...     ...
11995  valentine cupid vampire- jena ian another vamp...       1
11996  read seven books series apocalypticadventure o...       1
11997  book really wasnt cuppa situation man capturin...       0
11998  tried use charge kindle didnt even register ch...       0
11999  taking instruction look often hidden world sex...       0

[12000 rows x 2 columns]

In [39]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [42]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [43]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])


In [44]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

/tmp/ipython-input-44-1959687590.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))


In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                              test_size=0.20)

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [48]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [50]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [52]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [53]:
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [54]:
confusion_matrix(y_test,y_pred_bow)

array([[908, 290],
       [624, 578]])

In [55]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.6191666666666666


In [56]:
confusion_matrix(y_test,y_pred_tfidf)

array([[960, 238],
       [773, 429]])

In [57]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.57875


In [59]:
from sklearn.naive_bayes import MultinomialNB

In [60]:
nb_model_bow_mnb=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf_mnb=GaussianNB().fit(X_train_tfidf,y_train)

In [61]:
y_pred_bow_mnb=nb_model_bow.predict(X_test_bow)

In [62]:
y_pred_tfidf_mnb=nb_model_bow.predict(X_test_tfidf)

In [63]:
print("BOW accuracy using Multinomial: ",accuracy_score(y_test,y_pred_bow_mnb))

BOW accuracy using Multinomial:  0.6191666666666666


In [64]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf_mnb))

TFIDF accuracy:  0.57875
